"""shopping_list_per_user

Revision ID: db6026dae743
Revises: d4e7f2a1b8c3
Create Date: 2026-05-07 17:06:20.057715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6026dae743'
down_revision: Union[str, None] = 'd4e7f2a1b8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_shopping_list_date_user', 'shopping_lists', ['list_date', 'created_by'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_shopping_list_date_user', 'shopping_lists', type_='unique')
    # ### end Alembic commands ###
