"""initial_schema

Revision ID: f1edba3d559c
Revises: 
Create Date: 2026-05-03 19:40:30.219864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models import UUID   


# revision identifiers, used by Alembic.
revision: str = 'f1edba3d559c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('clients',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by',UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clients_is_active', 'clients', ['is_active'], unique=False)
    op.create_index('idx_clients_name', 'clients', ['name'], unique=False)
    op.create_table('providers',
    sa.Column('id',UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by',UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_providers_is_active', 'providers', ['is_active'], unique=False)
    op.create_index('idx_providers_name', 'providers', ['name'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id',UUID(), nullable=False),
    sa.Column('user_id',UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('shopping_lists',
    sa.Column('id',UUID(), nullable=False),
    sa.Column('list_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by',UUID(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_date')
    )
    op.create_index('idx_shopping_lists_list_date', 'shopping_lists', ['list_date'], unique=False)
    op.create_index('idx_shopping_lists_status', 'shopping_lists', ['status'], unique=False)
    op.create_table('user_identities',
    sa.Column('id',UUID(), nullable=False),
    sa.Column('user_id',UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('linked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_user_identities_provider')
    )
    op.create_index('idx_user_identities_provider', 'user_identities', ['provider', 'provider_user_id'], unique=False)
    op.create_index('idx_user_identities_user_id', 'user_identities', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id',UUID(), nullable=False),
    sa.Column('client_id',UUID(), nullable=False),
    sa.Column('created_by',UUID(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('raw_whatsapp_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_client_id', 'orders', ['client_id'], unique=False)
    op.create_index('idx_orders_created_by', 'orders', ['created_by'], unique=False)
    op.create_index('idx_orders_order_date', 'orders', ['order_date'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_table('products',
    sa.Column('id',UUID(), nullable=False),
    sa.Column('provider_id',UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by',UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_products_is_active', 'products', ['is_active'], unique=False)
    op.create_index('idx_products_name', 'products', ['name'], unique=False)
    op.create_index('idx_products_provider_id', 'products', ['provider_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id',UUID(), nullable=False),
    sa.Column('shopping_list_id',UUID(), nullable=False),
    sa.Column('provider_id',UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('created_by',UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shopping_list_id', 'provider_id', name='uq_purchase_orders_list_provider')
    )
    op.create_index('idx_purchase_orders_provider_id', 'purchase_orders', ['provider_id'], unique=False)
    op.create_index('idx_purchase_orders_shopping_list_id', 'purchase_orders', ['shopping_list_id'], unique=False)
    op.create_index('idx_purchase_orders_status', 'purchase_orders', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('id',UUID(), nullable=False),
    sa.Column('order_id',UUID(), nullable=False),
    sa.Column('client_id',UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('created_by',UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index('idx_invoices_client_id', 'invoices', ['client_id'], unique=False)
    op.create_index('idx_invoices_invoice_number', 'invoices', ['invoice_number'], unique=False)
    op.create_index('idx_invoices_order_id', 'invoices', ['order_id'], unique=False)
    op.create_index('idx_invoices_status', 'invoices', ['status'], unique=False)
    op.create_table('order_items',
    sa.Column('id',UUID(), nullable=False),
    sa.Column('order_id',UUID(), nullable=False),
    sa.Column('product_id',UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'product_id', name='uq_order_items_order_product')
    )
    op.create_index('idx_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('idx_order_items_product_id', 'order_items', ['product_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id',UUID(), nullable=False),
    sa.Column('purchase_order_id',UUID(), nullable=False),
    sa.Column('product_id',UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_order_id', 'product_id', name='uq_po_items_order_product')
    )
    op.create_index('idx_po_items_purchase_order_id', 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_table('shopping_list_items',
    sa.Column('id',UUID(), nullable=False),
    sa.Column('shopping_list_id',UUID(), nullable=False),
    sa.Column('product_id',UUID(), nullable=False),
    sa.Column('provider_id',UUID(), nullable=False),
    sa.Column('total_quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('adjusted_quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shopping_list_id', 'product_id', name='uq_shopping_list_items_list_product')
    )
    op.create_index('idx_shopping_list_items_list_id', 'shopping_list_items', ['shopping_list_id'], unique=False)
    op.create_index('idx_shopping_list_items_provider_id', 'shopping_list_items', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_shopping_list_items_provider_id', table_name='shopping_list_items')
    op.drop_index('idx_shopping_list_items_list_id', table_name='shopping_list_items')
    op.drop_table('shopping_list_items')
    op.drop_index('idx_po_items_purchase_order_id', table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index('idx_order_items_product_id', table_name='order_items')
    op.drop_index('idx_order_items_order_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('idx_invoices_status', table_name='invoices')
    op.drop_index('idx_invoices_order_id', table_name='invoices')
    op.drop_index('idx_invoices_invoice_number', table_name='invoices')
    op.drop_index('idx_invoices_client_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('idx_purchase_orders_status', table_name='purchase_orders')
    op.drop_index('idx_purchase_orders_shopping_list_id', table_name='purchase_orders')
    op.drop_index('idx_purchase_orders_provider_id', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index('idx_products_provider_id', table_name='products')
    op.drop_index('idx_products_name', table_name='products')
    op.drop_index('idx_products_is_active', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_order_date', table_name='orders')
    op.drop_index('idx_orders_created_by', table_name='orders')
    op.drop_index('idx_orders_client_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_user_identities_user_id', table_name='user_identities')
    op.drop_index('idx_user_identities_provider', table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index('idx_shopping_lists_status', table_name='shopping_lists')
    op.drop_index('idx_shopping_lists_list_date', table_name='shopping_lists')
    op.drop_table('shopping_lists')
    op.drop_index('idx_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_providers_name', table_name='providers')
    op.drop_index('idx_providers_is_active', table_name='providers')
    op.drop_table('providers')
    op.drop_index('idx_clients_name', table_name='clients')
    op.drop_index('idx_clients_is_active', table_name='clients')
    op.drop_table('clients')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
